In [54]:
import pandas as pd

In [55]:
df = pd.read_csv('imf_indicators.csv')

In [56]:
df

,country_code,year,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
0,ABW,2010,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
1,ABW,2011,-10.0,2.638,3.6,4.4,8.9,59.3,0.108,imf_datamapper_v1
2,ABW,2012,3.6,2.615,-1.2,0.6,9.6,65.5,0.107,imf_datamapper_v1
3,ABW,2013,-12.0,2.728,7.1,-2.4,7.6,70.0,0.107,imf_datamapper_v1
4,ABW,2014,-4.8,2.791,1.4,0.4,7.5,77.7,0.108,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...,...
3178,ZWE,2019,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
3179,ZWE,2020,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
3180,ZWE,2021,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
3181,ZWE,2022,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
3182,ZWE,2023,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [57]:
df.shape

(3183, 10)

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3183 entries, 0 to 3182
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_code             3183 non-null   str
 1   year                     3183 non-null   int64
 2   current_account_pct_gdp  3129 non-null   float64
 3   gdp_usd_bn               3183 non-null   float64
 4   gdp_growth_pct           3180 non-null   float64
 5   inflation_avg_pct        3158 non-null   float64
 6   unemployment_pct         1644 non-null   float64
 7   govt_gross_debt_gdp      3145 non-null   float64
 8   population_millions      3182 non-null   float64
 9   source_engine            3183 non-null   str
dtypes: float64(7), int64(1), str(2)
memory usage: 248.8 KB

In [59]:
pd.set_option('display.max_columns',10)

In [60]:
df

,country_code,year,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
0,ABW,2010,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
1,ABW,2011,-10.0,2.638,3.6,4.4,8.9,59.3,0.108,imf_datamapper_v1
2,ABW,2012,3.6,2.615,-1.2,0.6,9.6,65.5,0.107,imf_datamapper_v1
3,ABW,2013,-12.0,2.728,7.1,-2.4,7.6,70.0,0.107,imf_datamapper_v1
4,ABW,2014,-4.8,2.791,1.4,0.4,7.5,77.7,0.108,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...,...
3178,ZWE,2019,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
3179,ZWE,2020,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
3180,ZWE,2021,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
3181,ZWE,2022,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
3182,ZWE,2023,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [61]:
df

,country_code,year,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
0,ABW,2010,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
1,ABW,2011,-10.0,2.638,3.6,4.4,8.9,59.3,0.108,imf_datamapper_v1
2,ABW,2012,3.6,2.615,-1.2,0.6,9.6,65.5,0.107,imf_datamapper_v1
3,ABW,2013,-12.0,2.728,7.1,-2.4,7.6,70.0,0.107,imf_datamapper_v1
4,ABW,2014,-4.8,2.791,1.4,0.4,7.5,77.7,0.108,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...,...
3178,ZWE,2019,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
3179,ZWE,2020,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
3180,ZWE,2021,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
3181,ZWE,2022,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
3182,ZWE,2023,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [62]:
df.tail(10)

,country_code,year,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
3173,ZWE,2014,-8.3,28.248,2.4,-0.2,NaN,29.2,13.778,imf_datamapper_v1
3174,ZWE,2015,-5.7,28.123,1.8,-2.4,NaN,34.1,14.075,imf_datamapper_v1
3175,ZWE,2016,-2.4,29.257,0.8,-1.6,NaN,35.1,14.371,imf_datamapper_v1
3176,ZWE,2017,-0.9,31.018,5.2,0.9,NaN,49.0,14.668,imf_datamapper_v1
3177,ZWE,2018,-2.6,53.914,5.0,10.6,NaN,33.0,14.968,imf_datamapper_v1
3178,ZWE,2019,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
3179,ZWE,2020,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
3180,ZWE,2021,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
3181,ZWE,2022,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
3182,ZWE,2023,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [63]:
df.iloc[[0,1,2],0:5]

  country_code  year  current_account_pct_gdp  gdp_usd_bn  gdp_growth_pct
0          ABW  2010                    -18.7       2.454            -3.3
1          ABW  2011                    -10.0       2.638             3.6
2          ABW  2012                      3.6       2.615            -1.2

In [64]:
df.loc[0:2,['country_code','year']]

  country_code  year
0          ABW  2010
1          ABW  2011
2          ABW  2012

In [65]:
df.set_index('year')

,country_code,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
year,,,,,,,,,
2010,ABW,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
2011,ABW,-10.0,2.638,3.6,4.4,8.9,59.3,0.108,imf_datamapper_v1
2012,ABW,3.6,2.615,-1.2,0.6,9.6,65.5,0.107,imf_datamapper_v1
2013,ABW,-12.0,2.728,7.1,-2.4,7.6,70.0,0.107,imf_datamapper_v1
2014,ABW,-4.8,2.791,1.4,0.4,7.5,77.7,0.108,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...
2019,ZWE,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
2020,ZWE,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
2021,ZWE,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
2022,ZWE,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
2023,ZWE,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [66]:
df

,country_code,year,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
0,ABW,2010,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
1,ABW,2011,-10.0,2.638,3.6,4.4,8.9,59.3,0.108,imf_datamapper_v1
2,ABW,2012,3.6,2.615,-1.2,0.6,9.6,65.5,0.107,imf_datamapper_v1
3,ABW,2013,-12.0,2.728,7.1,-2.4,7.6,70.0,0.107,imf_datamapper_v1
4,ABW,2014,-4.8,2.791,1.4,0.4,7.5,77.7,0.108,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...,...
3178,ZWE,2019,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
3179,ZWE,2020,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
3180,ZWE,2021,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
3181,ZWE,2022,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
3182,ZWE,2023,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [67]:
df.set_index('year', inplace= True)

In [68]:
df

,country_code,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
year,,,,,,,,,
2010,ABW,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
2011,ABW,-10.0,2.638,3.6,4.4,8.9,59.3,0.108,imf_datamapper_v1
2012,ABW,3.6,2.615,-1.2,0.6,9.6,65.5,0.107,imf_datamapper_v1
2013,ABW,-12.0,2.728,7.1,-2.4,7.6,70.0,0.107,imf_datamapper_v1
2014,ABW,-4.8,2.791,1.4,0.4,7.5,77.7,0.108,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...
2019,ZWE,2.3,39.776,-6.3,255.3,NaN,53.9,15.268,imf_datamapper_v1
2020,ZWE,1.7,39.962,-7.8,557.2,NaN,56.8,15.582,imf_datamapper_v1
2021,ZWE,0.7,52.413,8.5,98.5,NaN,39.9,15.904,imf_datamapper_v1
2022,ZWE,0.6,48.570,6.1,193.4,NaN,66.8,16.229,imf_datamapper_v1
2023,ZWE,0.3,44.372,5.3,667.4,NaN,76.1,16.624,imf_datamapper_v1

In [69]:
df.sort_index(ascending = False, inplace=True)

In [70]:
df

,country_code,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
year,,,,,,,,,
2023,LBR,-20.1,4.390,4.6,10.1,NaN,57.2,5.493,imf_datamapper_v1
2023,EUQ,2.0,26028.485,1.2,6.3,NaN,76.0,738.567,imf_datamapper_v1
2023,IND,-0.7,3500.906,7.2,5.4,4.9,85.0,1438.070,imf_datamapper_v1
2023,IDN,-0.1,1371.167,5.0,3.7,5.3,39.6,278.696,imf_datamapper_v1
2023,HUN,-0.1,213.315,-0.8,17.1,4.1,73.2,9.600,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...
2010,JPN,3.8,5811.577,4.1,-0.7,5.1,178.6,127.594,imf_datamapper_v1
2010,KAZ,1.8,148.047,7.3,7.1,5.8,10.7,16.322,imf_datamapper_v1
2010,TUR,-5.7,783.025,8.5,8.6,11.0,38.6,73.142,imf_datamapper_v1
2010,KEN,-5.2,45.406,8.1,4.1,NaN,36.7,38.600,imf_datamapper_v1
2010,ABW,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1

In [71]:
df.reset_index(inplace=True)

In [72]:
df.columns

Index(['year', 'country_code', 'current_account_pct_gdp', 'gdp_usd_bn',
       'gdp_growth_pct', 'inflation_avg_pct', 'unemployment_pct',
       'govt_gross_debt_gdp', 'population_millions', 'source_engine'],
      dtype='str')

In [73]:
filt = (df['year'].isin([2010, 2023]) & (df['gdp_growth_pct'] >= 5))

In [74]:
df.loc[filt, 'source_engine'].count()

np.int64(164)

In [75]:
df.rename(columns = {'country_code':'CC'},inplace= True)

In [76]:
df.CC

0       LBR
1       EUQ
2       IND
3       IDN
4       HUN
       ...
3178    JPN
3179    KAZ
3180    TUR
3181    KEN
3182    ABW
Name: CC, Length: 3183, dtype: str

In [77]:
df.CC = df.CC.replace({'IND':'BHA'})

In [78]:
df

,year,CC,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
0,2023,LBR,-20.1,4.390,4.6,10.1,NaN,57.2,5.493,imf_datamapper_v1
1,2023,EUQ,2.0,26028.485,1.2,6.3,NaN,76.0,738.567,imf_datamapper_v1
2,2023,BHA,-0.7,3500.906,7.2,5.4,4.9,85.0,1438.070,imf_datamapper_v1
3,2023,IDN,-0.1,1371.167,5.0,3.7,5.3,39.6,278.696,imf_datamapper_v1
4,2023,HUN,-0.1,213.315,-0.8,17.1,4.1,73.2,9.600,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...,...
3178,2010,JPN,3.8,5811.577,4.1,-0.7,5.1,178.6,127.594,imf_datamapper_v1
3179,2010,KAZ,1.8,148.047,7.3,7.1,5.8,10.7,16.322,imf_datamapper_v1
3180,2010,TUR,-5.7,783.025,8.5,8.6,11.0,38.6,73.142,imf_datamapper_v1
3181,2010,KEN,-5.2,45.406,8.1,4.1,NaN,36.7,38.600,imf_datamapper_v1
3182,2010,ABW,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1

In [79]:
df.sort_values(by='year',ascending=True)

,year,CC,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
3182,2010,ABW,-18.7,2.454,-3.3,2.1,10.6,54.7,0.109,imf_datamapper_v1
3037,2010,TCD,-2.9,14.070,13.8,-2.1,NaN,22.9,11.952,imf_datamapper_v1
3036,2010,MNG,-12.3,7.185,7.3,8.3,9.9,31.0,2.761,imf_datamapper_v1
3035,2010,NOR,11.4,440.133,1.0,2.4,3.8,42.1,4.908,imf_datamapper_v1
3034,2010,NMQ,-2.8,17870.126,2.9,1.9,NaN,90.9,462.174,imf_datamapper_v1
...,...,...,...,...,...,...,...,...,...,...
146,2023,TUR,-3.6,1153.295,5.0,53.9,9.4,28.2,85.326,imf_datamapper_v1
145,2023,VEN,5.8,102.378,4.0,337.5,NaN,138.5,26.740,imf_datamapper_v1
144,2023,VUT,-7.8,1.198,5.8,11.2,NaN,39.2,0.319,imf_datamapper_v1
142,2023,WE,-1.2,6614.744,2.3,14.8,NaN,73.5,643.806,imf_datamapper_v1
0,2023,LBR,-20.1,4.390,4.6,10.1,NaN,57.2,5.493,imf_datamapper_v1

In [80]:
df.nlargest(10,'gdp_growth_pct')

,year,CC,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
2623,2012,LBY,25.8,92.542,86.8,6.1,NaN,NaN,6.179,imf_datamapper_v1
53,2023,MAC,31.4,45.627,75.3,0.9,2.7,0.0,0.684,imf_datamapper_v1
310,2022,GUY,25.9,14.718,63.3,6.9,NaN,24.8,0.896,imf_datamapper_v1
736,2020,GUY,-17.3,5.471,43.5,0.7,NaN,47.4,0.860,imf_datamapper_v1
571,2021,MDV,-8.7,5.240,37.5,0.2,NaN,123.4,0.384,imf_datamapper_v1
9,2023,GUY,9.9,16.919,33.8,2.8,NaN,26.7,0.918,imf_datamapper_v1
1404,2017,LBY,6.6,67.153,32.5,25.8,NaN,NaN,6.739,imf_datamapper_v1
2275,2014,ERI,17.7,2.604,30.9,8.4,NaN,204.5,3.311,imf_datamapper_v1
621,2021,LBY,11.4,35.216,27.3,2.9,NaN,NaN,7.135,imf_datamapper_v1
2466,2013,SSD,-3.9,14.947,27.3,-2.7,NaN,17.6,11.166,imf_datamapper_v1

In [81]:
country_grp = df.groupby('CC')

In [89]:
country_grp.groups

{'ABW': [225, 415, 504, 851, 943, 1253, 1580, 1749, 1956, 2099, 2289, 2504, 2944, 3182], 'ADVEC': [222, 445, 575, 774, 1021, 1167, 1588, 1747, 1899, 2185, 2431, 2516, 2738, 3127], 'AFG': [213, 366, 529, 780, 1076, 1289, 1574, 1653, 2042, 2165, 2340, 2508, 2922, 3154], 'AFQ': [215, 253, 560, 873, 915, 1307, 1401, 1601, 1980, 2083, 2334, 2521, 2899, 3079], 'AGO': [221, 432, 494, 845, 1112, 1279, 1469, 1617, 2045, 2048, 2326, 2686, 2885, 3065], 'ALB': [212, 248, 540, 776, 1125, 1145, 1521, 1597, 1841, 2077, 2395, 2705, 2836, 3089], 'AND': [216, 236, 670, 757, 1056, 1158, 1585, 1660, 1859, 2214, 2474, 2580, 2851, 3028], 'APQ': [219, 394, 552, 709, 1078, 1139, 1367, 1671, 1939, 2183, 2346, 2641, 2911, 3050], 'ARE': [223, 263, 555, 811, 1029, 1326, 1389, 1767, 1967, 2272, 2327, 2622, 2906, 3157], 'ARG': [218, 299, 675, 783, 1061, 1136, 1533, 1765, 2007, 2201, 2375, 2645, 2732, 3177], 'ARM': [217, 229, 526, 753, 946, 1312, 1468, 1721, 1912, 2168, 2485, 2599, 2774, 3117], 'AS5': [220, 391, 537, 695, 942, 1194, 1517, 1773, 1915, 2249, 2418, 2662, 2816, 3123], 'ATG': [224, 231, 543, 848, 1111, 1166, 1516, 1711, 1869, 2138, 2420, 2689, 2742, 2968], 'AUS': [226, 333, 658, 890, 1031, 1338, 1589, 1738, 1839, 2078, 2493, 2625, 2761, 3000], 'AUT': [214, 360, 636, 824, 963, 1362, 1380, 1777, 1937, 2122, 2364, 2660, 2853, 3005], 'AZE': [106, 397, 615, 904, 964, 1282, 1385, 1796, 1982, 2071, 2313, 2551, 2882, 2966], 'AZQ': [210, 406, 610, 901, 1124, 1351, 1384, 1791, 1979, 2075, 2306, 2711, 2878, 2961], 'BDI': [77, 416, 604, 838, 1072, 1246, 1409, 1805, 1974, 2081, 2312, 2671, 2866, 2963], 'BEL': [76, 359, 600, 836, 1116, 1174, 1400, 1789, 1970, 2063, 2316, 2698, 2869, 2975], 'BEN': [75, 369, 637, 825, 1084, 1341, 1393, 1776, 1989, 2049, 2360, 2690, 2901, 2969], 'BFA': [74, 376, 631, 816, 954, 1354, 1377, 1782, 2003, 2052, 2365, 2699, 2895, 2957], 'BGD': [73, 385, 626, 829, 973, 1299, 1411, 1787, 1994, 2060, 2325, 2663, 2893, 2997], 'BGR': [72, 435, 622, 879, 914, 1316, 1406, 1816, 1992, 2127, 2336, 2673, 2888, 3002], 'BHA': [2, 327, 652, 755, 1055, 1148, 1571, 1728, 2021, 2205, 2462, 2570, 2813, 3167], 'BHR': [71, 440, 572, 883, 925, 1329, 1398, 1812, 1978, 2131, 2356, 2720, 2841, 3008], 'BHS': [70, 453, 567, 875, 1058, 1155, 1396, 1817, 1945, 2092, 2343, 2715, 2839, 3009], 'BIH': [69, 257, 562, 863, 999, 1180, 1417, 1707, 1938, 2144, 2331, 2717, 2833, 3013], 'BLR': [68, 266, 556, 866, 984, 1195, 1408, 1714, 1934, 2139, 2319, 2582, 2829, 2996], 'BLZ': [67, 273, 594, 872, 1004, 1200, 1368, 1719, 1950, 2102, 2368, 2590, 2862, 2981], 'BOL': [66, 282, 589, 871, 1012, 1199, 1556, 1701, 1965, 2103, 2363, 2595, 2859, 2985], 'BRA': [65, 232, 585, 868, 1019, 1187, 1551, 1684, 1958, 2112, 2352, 2602, 2854, 2989], 'BRB': [64, 243, 579, 864, 986, 1196, 1564, 1690, 1954, 2115, 2347, 2556, 2848, 2993], 'BRN': [63, 239, 669, 861, 996, 1238, 1561, 1696, 2030, 2051, 2286, 2563, 2940, 2994], 'BTN': [62, 334, 664, 859, 1046, 1222, 1530, 1748, 2010, 2107, 2315, 2567, 2945, 2991], 'BWA': [61, 325, 654, 857, 1045, 1147, 1537, 1755, 2008, 2098, 2308, 2576, 2955, 2978], 'CAF': [60, 345, 647, 891, 1054, 1178, 1539, 1760, 2033, 2146, 2302, 2607, 2907, 2995], 'CAN': [59, 331, 641, 888, 1030, 1171, 1545, 1763, 2020, 2143, 2298, 2640, 2914, 3014], 'CAQ': [58, 288, 649, 885, 1039, 1137, 1528, 1724, 2032, 2093, 2473, 2647, 2905, 3010], 'CBQ': [57, 305, 655, 882, 927, 1333, 1577, 1732, 2015, 2089, 2470, 2656, 2932, 2998], 'CHE': [56, 313, 666, 878, 936, 1360, 1578, 1734, 2018, 2084, 2461, 2632, 2824, 2977], 'CHL': [55, 314, 474, 865, 911, 1313, 1478, 1743, 1929, 2070, 2453, 2612, 2923, 2960], 'CHN': [78, 304, 486, 853, 940, 1265, 1458, 1737, 1851, 2076, 2445, 2617, 2913, 2973], 'CIV': [79, 301, 461, 831, 968, 1305, 1455, 1731, 1847, 2087, 2497, 2627, 2947, 2971], 'CMQ': [80, 348, 528, 815, 979, 1294, 1526, 1727, 1846, 2054, 2496, 2630, 2825, 2986], 'CMR': [93, 324, 542, 823, 949, 1259, 1466, 1764, 1828, 2061, 2476, 2619, 2756, 2972], 'COD': [103, 335, 499, 821, 958, 1320, 1452, 1758, 1843, 2142, 2481, 2658, 2748, 2965], 'COG': [102, 250, 511, 819, 1123, 1319, 1437, 1753, 1906, 2123, 2479, 2649, 2736, 3001], 'COL': [101, 233, 532, 817, 1065, 1286, 1441, 1700, 1918, 2100, 2440, 2636, 2801, 3011], 'COM': [100, 278, 546, 852, 1101, 1252, 1446, 1694, 1901, 2120, 2400, 2574, 2807, 2987], 'CPV': [99, 268, 463, 849, 1091, 1311, 1447, 1689, 1879, 2133, 2397, 2561, 2818, 2984], 'CRI': [98, 256, 477, 846, 1120, 1323, 1430, 1683, 1883, 2119, 2393, 2578, 2780, 2976], 'CYP': [97, 444, 492, 842, 1079, 1160, 1507, 1678, 1894, 2109, 2385, 2603, 2771, 2992], 'CZE': [96, 429, 548, 840, 1096, 1223, 1504, 1717, 1900, 2101, 2407, 2593, 2779, 2988], 'DA': [95, 421, 458, 837, 1077, 1248, 1522, 1712, 1917, 2097, 2408, 2566, 2790, 2983], 'DEU': [94, 375, 508, 835, 912, 1213, 1515, 1709, 1834, 2150, 2435, 2707, 2785, 3007], 'DJI': [92, 368, 551, 897, 1118, 1261, 1484, 1769, 1849, 2145, 2432, 2723, 2775, 3012], 'DMA': [81, 419, 497, 902, 971, 1291, 1487, 1813, 1833, 2136, 2422, 2702, 2793, 3006], 'DNK': [91, 405, 471, 896, 1034, 1152, 1493, 1808, 1873, 2094, 2413, 2695, 2808, 3004], 'DOM': [90, 393, 473, 900, 987, 1240, 1496, 1784, 1895, 2091, 2411, 2693, 2763, 2962], 'DZA': [89, 396, 475, 718, 1003, 1185, 1499, 1775, 1919, 2055, 2428, 2701, 2749, 2959], 'EAQ': [88, 403, 487, 711, 1057, 1150, 1494, 1790, 1910, 2065, 2380, 2635, 2733, 2970], 'ECU': [87, 418, 465, 737, 937, 1363, 1492, 1806, 1840, 2088, 2398, 2724, 2904, 3017], 'EDE': [86, 388, 531, 738, 947, 1302, 1488, 1801, 1826, 2082, 2489, 2704, 2740, 3059], 'EEQ': [85, 371, 524, 689, 1098, 1256, 1485, 1677, 1852, 2072, 2464, 2706, 2734, 3124], 'EGY': [84, 380, 509, 700, 1080, 1242, 1481, 1794, 1863, 2265, 2471, 2722, 2751, 3125], 'ERI': [1109, 1198, 1502, 1797, 1860, 2275, 2469, 2677, 2745, 3128], 'ESP': [83, 442, 520, 685, 1082, 1191, 1524, 1803, 1821, 2237, 2447, 2667, 2755, 3129], 'EST': [82, 439, 516, 792, 1066, 1241, 1520, 1800, 1842, 2256, 2482, 2680, 2758, 3130], 'ETH': [54, 449, 536, 814, 1089, 1230, 1514, 1772, 1903, 2240, 2406, 2684, 2730, 3132], 'EU': [52, 433, 457, 795, 1069, 1177, 1511, 1809, 1914, 2261, 2394, 2685, 2795, 3133], 'EUQ': [1, 448, 476, 808, 1122, 1176, 1508, 1785, 1878, 2241, 2426, 2688, 2799, 3134], 'EURO': [51, 259, 480, 803, 1115, 1330, 1479, 1811, 1898, 2255, 2412, 2696, 2802, 3135], 'FIN': [24, 270, 460, 756, 1103, 1344, 1451, 1819, 1904, 2238, 2419, 2681, 2809, 3137], 'FJI': [23, 272, 498, 750, 1092, 1271, 1448, 1818, 1824, 2258, 2421, 2665, 2812, 3138], 'FRA': [22, 252, 513, 773, 1067, 1304, 1445, 1705, 1854, 2262, 2430, 2672, 2820, 3139], 'FSM': [21, 227, 522, 766, 1081, 1277, 1442, 1710, 1844, 2264, 2433, 2679, 2767, 3121], 'GAB': [20, 241, 510, 762, 1121, 1349, 1438, 1713, 1867, 2232, 2438, 2703, 2768, 3102], 'GBR': [19, 286, 505, 769, 1062, 1335, 1434, 1768, 1881, 2180, 2410, 2729, 2773, 3120], 'GEO': [18, 329, 549, 745, 955, 1355, 1431, 1698, 1896, 2186, 2382, 2713, 2777, 3103], 'GHA': [17, 342, 539, 802, 948, 1266, 1454, 1681, 1893, 2188, 2384, 2710, 2783, 3105], 'GIN': [16, 344, 534, 812, 952, 1288, 1473, 1685, 1889, 2191, 2386, 2728, 2789, 3106], 'GMB': [15, 354, 495, 790, 978, 1293, 1470, 1693, 1876, 2172, 2391, 2661, 2792, 3107], 'GNB': [14, 295, 456, 697, 970, 1303, 1465, 1697, 1922, 2158, 2399, 2585, 2806, 3108], 'GNQ': [13, 308, 491, 725, 965, 1281, 1462, 1746, 1916, 2155, 2441, 2586, 2788, 3110], 'GRC': [12, 311, 484, 735, 919, 1263, 1459, 1754, 1905, 2166, 2442, 2588, 2786, 3111], 'GRD': [11, 317, 478, 712, 913, 1251, 1525, 1762, 1837, 2171, 2480, 2592, 2784, 3112], 'GTM': [10, 316, 673, 717, 924, 1350, 1590, 1745, 1827, 2217, 2490, 2597, 2782, 3113], 'GUY': [9, 310, 648, 736, 935, 1358, 1582, 1729, 1868, 2222, 2477, 2600, 2776, 3115], 'HKG': [8, 307, 650, 734, 931, 1322, 1581, 1735, 1856, 2225, 2502, 2604, 2772, 3116], 'HND': [7, 290, 660, 726, 966, 1331, 1575, 1740, 1820, 2231, 2444, 2555, 2770, 3118], 'HRV': [6, 298, 553, 693, 981, 1219, 1584, 1810, 1886, 2204, 2450, 2558, 2794, 3141], 'HTI': [5, 352, 671, 729, 1032, 1175, 1547, 1742, 1949, 2212, 2451, 2560, 2810, 3142], 'HUN': [4, 349, 643, 786, 1027, 1159, 1543, 1736, 2011, 2154, 2455, 2553, 2821, 3143], 'IDN': [3, 343, 661, 806, 1044, 1173, 1540, 1733, 2025, 2202, 2460, 2568, 2817, 3144], 'IRL': [25, 323, 645, 748, 1049, 1231, 1536, 1726, 2046, 2208, 2468, 2572, 2811, 3168], 'IRN': [26, 322, 667, 772, 1024, 1217, 1531, 1766, 2016, 2209, 2292, 2577, 2796, 3169], 'IRQ': [27, 228, 672, 768, 998, 1233, 1549, 1759, 2034, 2206, 2296, 2606, 2764, 3170], 'ISL': [40, 245, 578, 763, 991, 1243, 1569, 1756, 2029, 2195, 2300, 2637, 2803, 3172], 'ISR': [50, 238, 581, 765, 985, 1190, 1565, 1751, 2014, 2200, 2303, 2639, 2800, 3165], 'ITA': [49, 246, 577, 771, 1020, 1188, 1560, 1722, 2009, 2213, 2311, 2643, 2798, 3173], ...}

In [82]:
country_grp['year'].value_counts().loc['BHA']

year
2011    1
2013    1
2023    1
2016    1
2015    1
2021    1
2010    1
2014    1
2020    1
2019    1
2012    1
2018    1
2017    1
2022    1
Name: count, dtype: int64

In [83]:
df.head(50)

,year,CC,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
0,2023,LBR,-20.1,4.390,4.6,10.1,NaN,57.2,5.493,imf_datamapper_v1
1,2023,EUQ,2.0,26028.485,1.2,6.3,NaN,76.0,738.567,imf_datamapper_v1
2,2023,BHA,-0.7,3500.906,7.2,5.4,4.9,85.0,1438.070,imf_datamapper_v1
3,2023,IDN,-0.1,1371.167,5.0,3.7,5.3,39.6,278.696,imf_datamapper_v1
4,2023,HUN,-0.1,213.315,-0.8,17.1,4.1,73.2,9.600,imf_datamapper_v1
5,2023,HTI,-3.5,19.603,-1.9,44.1,NaN,27.8,12.227,imf_datamapper_v1
6,2023,HRV,0.1,85.647,3.8,8.4,6.2,60.9,3.860,imf_datamapper_v1
7,2023,HND,-4.0,34.356,3.6,6.7,6.4,41.7,10.645,imf_datamapper_v1
8,2023,HKG,8.4,380.762,3.2,2.1,3.0,6.3,7.528,imf_datamapper_v1
9,2023,GUY,9.9,16.919,33.8,2.8,NaN,26.7,0.918,imf_datamapper_v1
10,2023,GTM,3.1,104.354,3.5,6.2,NaN,27.2,18.125,imf_datamapper_v1
11,2023,GRD,-20.3,1.336,4.5,2.7,NaN,74.5,0.115,imf_datamapper_v1
12,2023,GRC,-6.8,243.016,2.1,4.2,11.1,165.5,10.414,imf_datamapper_v1
13,2023,GNQ,0.9,12.339,-5.1,2.4,NaN,39.1,1.544,imf_datamapper_v1
14,2023,GNB,-8.6,2.005,5.2,7.2,NaN,79.4,1.937,imf_datamapper_v1
15,2023,GMB,-5.4,2.331,5.9,17.0,NaN,77.4,2.719,imf_datamapper_v1
16,2023,GIN,-9.7,22.089,6.2,5.4,NaN,39.8,15.041,imf_datamapper_v1
17,2023,GHA,-0.8,80.547,3.1,39.2,NaN,79.1,33.788,imf_datamapper_v1
18,2023,GEO,-5.5,30.778,7.8,2.5,16.4,38.9,3.736,imf_datamapper_v1
19,2023,GBR,-3.6,3422.072,0.3,7.3,4.1,98.9,68.526,imf_datamapper_v1
20,2023,GAB,3.0,20.059,2.4,3.6,NaN,70.6,2.209,imf_datamapper_v1
21,2023,FSM,5.5,0.443,1.1,6.2,NaN,12.8,0.095,imf_datamapper_v1
22,2023,FRA,-1.0,3061.095,1.6,5.7,7.3,109.6,68.405,imf_datamapper_v1
23,2023,FJI,-6.6,5.477,9.4,3.0,6.5,82.9,0.917,imf_datamapper_v1
24,2023,FIN,-0.9,295.277,-1.3,4.3,7.2,77.0,5.564,imf_datamapper_v1
25,2023,IRL,7.0,567.537,-2.5,5.2,4.3,41.8,5.329,imf_datamapper_v1
26,2023,IRN,2.0,421.547,5.3,40.7,8.1,29.6,85.329,imf_datamapper_v1
27,2023,IRQ,5.8,270.799,0.9,4.4,NaN,42.1,43.324,imf_datamapper_v1
28,2023,KOR,1.8,1844.801,1.6,3.6,2.7,50.5,51.713,imf_datamapper_v1
29,2023,LUX,6.8,88.814,0.1,2.9,5.2,24.7,0.661,imf_datamapper_v1
30,2023,LTU,1.1,80.392,0.8,8.7,6.9,37.1,2.872,imf_datamapper_v1
31,2023,LSO,-0.8,2.227,2.5,6.5,NaN,61.1,2.311,imf_datamapper_v1
32,2023,LKA,1.7,83.723,-2.3,17.4,4.7,110.4,22.037,imf_datamapper_v1
33,2023,LIE,14.9,8.239,3.4,2.1,2.8,0.5,0.040,imf_datamapper_v1
34,2023,LCA,-2.2,2.397,3.3,3.8,NaN,75.2,0.179,imf_datamapper_v1
35,2023,LBY,4.2,43.958,10.5,2.4,NaN,NaN,7.306,imf_datamapper_v1
36,2023,LBN,-24.0,24.491,-0.7,221.3,11.5,185.8,5.354,imf_datamapper_v1
37,2023,LAO,2.7,14.993,3.7,31.2,NaN,108.9,7.582,imf_datamapper_v1
38,2023,KWT,31.1,165.474,-1.6,3.6,NaN,3.1,4.913,imf_datamapper_v1
39,2023,KNA,-13.7,1.034,4.6,3.6,NaN,60.0,0.051,imf_datamapper_v1
40,2023,ISL,-1.2,31.702,5.0,8.7,3.4,61.5,0.375,imf_datamapper_v1
41,2023,KIR,-1.8,0.292,3.3,9.3,NaN,11.3,0.125,imf_datamapper_v1
42,2023,KHM,1.3,42.404,5.0,2.1,NaN,26.3,17.424,imf_datamapper_v1
43,2023,KGZ,-44.9,15.187,9.0,10.8,4.0,42.0,6.931,imf_datamapper_v1
44,2023,KEN,-3.6,108.206,5.7,7.7,NaN,73.4,51.539,imf_datamapper_v1
45,2023,KAZ,-3.6,261.840,5.1,14.5,4.7,23.0,19.900,imf_datamapper_v1
46,2023,JPN,3.6,4384.854,0.7,3.3,2.6,220.3,124.482,imf_datamapper_v1
47,2023,JOR,-3.3,56.203,3.1,2.1,22.0,81.0,11.439,imf_datamapper_v1
48,2023,JAM,2.7,21.299,2.7,6.5,4.4,66.5,2.747,imf_datamapper_v1
49,2023,ITA,0.2,2317.550,0.9,5.9,7.7,133.9,58.997,imf_datamapper_v1

In [84]:
filt = (df.CC == 'JAM')

In [85]:
filt.value_counts()

CC
False    3169
True       14
Name: count, dtype: int64

In [91]:
country_grp.get_group('JAM')

,year,CC,current_account_pct_gdp,gdp_usd_bn,gdp_growth_pct,inflation_avg_pct,unemployment_pct,govt_gross_debt_gdp,population_millions,source_engine
48,2023,JAM,2.7,21.299,2.7,6.5,4.4,66.5,2.747,imf_datamapper_v1
279,2022,JAM,-0.7,18.710,6.4,10.3,6.3,70.2,2.743,imf_datamapper_v1
590,2021,JAM,0.9,15.982,5.7,5.9,8.4,86.3,2.740,imf_datamapper_v1
741,2020,JAM,-1.0,15.079,-8.3,5.2,10.2,101.3,2.737,imf_datamapper_v1
1014,2019,JAM,-1.8,17.002,1.8,3.9,7.7,87.7,2.734,imf_datamapper_v1
1197,2018,JAM,-1.4,16.767,2.5,3.7,9.1,88.3,2.731,imf_datamapper_v1
1557,2017,JAM,-2.5,15.726,2.3,4.4,11.7,95.1,2.726,imf_datamapper_v1
1695,2016,JAM,-0.3,14.931,2.8,2.3,13.2,106.9,2.722,imf_datamapper_v1
2031,2015,JAM,-2.9,14.927,1.4,3.7,13.5,115.9,2.719,imf_datamapper_v1
2227,2014,JAM,-7.8,14.225,0.6,8.3,13.8,134.4,2.716,imf_datamapper_v1
2284,2013,JAM,-9.3,14.582,0.2,9.4,15.3,135.2,2.713,imf_datamapper_v1
2650,2012,JAM,-9.5,15.149,-0.5,6.9,13.9,140.3,2.710,imf_datamapper_v1
2731,2011,JAM,-13.3,14.787,1.4,7.5,12.4,135.9,2.703,imf_datamapper_v1
3016,2010,JAM,-6.9,13.535,-1.4,12.6,12.4,137.8,2.696,imf_datamapper_v1

In [92]:
country_grp.gdp_growth_pct.median()

CC
ABW      3.35
ADVEC    2.05
AFG      2.45
AFQ      3.50
AGO      1.70
         ...
WSM      1.85
YEM      0.30
ZAF      1.50
ZMB      4.90
ZWE      5.10
Name: gdp_growth_pct, Length: 229, dtype: float64

In [ ]:
country_grp.gdp_growth_pct.median().loc['JAM']

np.float64(1.6)

In [95]:
country_grp.gdp_growth_pct.agg(['median','mean'])

       median      mean
CC
ABW      3.35  2.185714
ADVEC    2.05  1.978571
AFG      2.45  1.957143
AFQ      3.50  3.428571
AGO      1.70  2.057143
...       ...       ...
WSM      1.85  2.135714
YEM      0.30 -2.522222
ZAF      1.50  1.371429
ZMB      4.90  4.492857
ZWE      5.10  5.285714

[229 rows x 2 columns]